name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g npm-check-updates
    - run: ncu -u
    - run: npm install
    - run: npm test
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update Dependencies
        commit-message: Update dependencies
        labels: dependencies
